apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: platform-dev
spec:
  selector:
    app: platform-dev-front
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  